# Generated by Django 5.0.3 on 2024-03-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
        ('user', '0002_rename_is_doctor_user_is_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='user.user'),
        ),
    ]
