# Generated by Django 5.0.3 on 2024-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0005_paymentposting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditscore",
            name="crb",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditscore",
            name="credit_score",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditscore",
            name="number_of_loan",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
