# Generated by Django 5.0.3 on 2024-04-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0006_alter_creditscore_crb_alter_creditscore_credit_score_and_more"),
        ("userProfile", "0009_clientprofile_empolyee_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="userProfile.clientprofile",
            ),
        ),
    ]
