# Generated by Django 5.0.3 on 2024-04-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0007_alter_loan_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="monthly_interest",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="monthly_repayment",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="total_interest",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="total_repayment",
            field=models.FloatField(null=True),
        ),
    ]
