# Generated by Django 5.0.3 on 2024-04-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0008_loan_monthly_interest_loan_monthly_repayment_and_more"),
        ("userProfile", "0009_clientprofile_empolyee_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="balance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="userProfile.clientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="end_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("civil servant loans", "Civil Servant Loans"),
                    ("famers loans", "Famers Loans"),
                    ("micro business loans", "Micro Business Loans"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="method_of_payment",
            field=models.CharField(
                choices=[
                    ("mobile", "mobile"),
                    ("bank account", "Bank Account"),
                    ("credit card", "Credit Card"),
                    ("debit card", "Debit Card"),
                    ("loan", "Loan"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="start_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
