# Generated by Django 5.0.3 on 2024-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0009_alter_loan_amount_alter_loan_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=100,
                null=True,
            ),
        ),
    ]
