# Generated by Django 5.0.3 on 2024-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0010_alter_loan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="due_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="is_payment_made",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="status",
            field=models.CharField(
                choices=[("active", "Acctive"), ("closed", "Closed")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="paymentposting",
            name="is_payment_made",
            field=models.BooleanField(default=True),
        ),
    ]
