# Generated by Django 5.0.3 on 2024-04-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0011_loan_due_date_alter_loantransaction_is_payment_made_and_more"),
        ("userProfile", "0009_clientprofile_empolyee_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="status",
            field=models.CharField(
                choices=[("active", "Acctive"), ("closed", "Closed")],
                default="active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="paymentposting",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="userProfile.clientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="paymentposting",
            name="loan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="userProfile.clientprofile",
            ),
        ),
    ]
