# Generated by Django 5.0.3 on 2024-04-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0012_alter_loantransaction_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="loan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan",
                to="loan.loan",
            ),
        ),
    ]
