# Generated by Django 5.0.3 on 2024-04-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0015_alter_loantransaction_loan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Acctive"),
                    ("closed", "Closed"),
                    ("bad debt", "Bad debt"),
                ],
                default="active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="paymentposting",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Disbursement", "Disbursement,"),
                    ("Loan Repayment", "Loan Repayment"),
                    ("Penalty", "Penalty"),
                    ("bad debt", "Bad debt"),
                ],
                max_length=255,
            ),
        ),
    ]
