# Generated by Django 5.0.3 on 2024-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0016_alter_loantransaction_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Disbursement", "Disbursement,"),
                    ("Loan Repayment", "Loan Repayment"),
                    ("Penalty", "Penalty"),
                    ("bad debt", "Bad Debt"),
                ],
                max_length=255,
            ),
        ),
    ]
