# Generated by Django 5.0.3 on 2024-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_rename_agenprofile_agentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='credit_score',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
