# Generated by Django 5.0.3 on 2024-03-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_clientprofile_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='bank_acc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
