# Generated by Django 5.0.3 on 2024-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_clientprofile_bank_clientprofile_bank_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='bank_acc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
