# Generated by Django 5.0.3 on 2024-03-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_agentprofile_bank_agentprofile_bank_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
