# Generated by Django 5.0.3 on 2024-04-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_agentprofile_is_agent_clientprofile_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
