# Generated by Django 5.0.3 on 2024-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0008_alter_clientprofile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="empolyee_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
